name = "[GM] Extras - Bundeswehr"
author = "erem2k"
prefix = "gme_bw"

[files]
include = [
	"mod.cpp",
	"README.md",
	"LICENSE.md",
	"gme_bw_logo_small.paa",
	"gme_bw_logo.paa",
	"gme_bw_logo_over.paa",
	"gme_bw_picture.paa"
]
exclude = [
	"*.jpg",
	"*.png",
	"*.psd",
	"*.xcf"
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.build]
pdrive = "require"

[hemtt.release]
sign = true
archive = true

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
